[package]
name = "wallpaper"
version = "2.0.1"
authors = ["reujab <reujab@gmail.com>"]
description = "Gets and sets the desktop wallpaper/background."
repository = "https://github.com/reujab/wallpaper.rs"
readme = "readme.md"
keywords = ["desktop", "wallpaper", "background"]
categories = ["api-bindings"]
license = "Unlicense"

[features]
default = ["from_url"]
from_url = ["reqwest", "url"]

[target.'cfg(any(unix, windows))'.dependencies]
dirs = "3.0.1"
reqwest = { version = "0.10.8", optional = true, features = ["blocking"] }
url = { version = "2.1.1", optional = true }

[target.'cfg(unix)'.dependencies]
enquote = "1"

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies]
rust-ini = "0.15.3"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }
